/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

/**
 *
 * @author xp
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    double operando1 = 0;   //primer operando
    
    String operacion = "";  //guarda qué operación se ha pulsado
    
    /**
     * Creates new form VentanaCalculadora
     */
    public VentanaCalculadora() {
        initComponents();
    }

    private void numeroPulsado(String numero){
        if (pantalla.getText() == "0"){
             pantalla.setText(numero);
        }
        else {
              pantalla.setText(pantalla.getText() + numero);
        }
    }

    private void operacionPulsada(String _operacion){
        operacion = _operacion;
        
        //convierto lo que hay escrito en la pantalla (que es un numero pero que ahora mismo es un String)
        //a su equivalente double, para poder operar con él
        operando1 = Double.valueOf( pantalla.getText()) ;
        
        //borro la pantalla
        pantalla.setText("0");
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        boton07 = new javax.swing.JButton();
        boton08 = new javax.swing.JButton();
        boton09 = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        boton04 = new javax.swing.JButton();
        boton05 = new javax.swing.JButton();
        boton06 = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        boton01 = new javax.swing.JButton();
        boton02 = new javax.swing.JButton();
        boton03 = new javax.swing.JButton();
        botonPor = new javax.swing.JButton();
        boton00 = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setBackground(new java.awt.Color(0, 0, 0));
        pantalla.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        pantalla.setForeground(new java.awt.Color(102, 255, 51));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");
        pantalla.setToolTipText("");
        pantalla.setOpaque(true);

        boton07.setBackground(new java.awt.Color(153, 153, 153));
        boton07.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton07.setForeground(new java.awt.Color(255, 255, 255));
        boton07.setText("7");
        boton07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton07MousePressed(evt);
            }
        });

        boton08.setBackground(new java.awt.Color(153, 153, 153));
        boton08.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton08.setForeground(new java.awt.Color(255, 255, 255));
        boton08.setText("8");
        boton08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton08MousePressed(evt);
            }
        });

        boton09.setBackground(new java.awt.Color(153, 153, 153));
        boton09.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton09.setForeground(new java.awt.Color(255, 255, 255));
        boton09.setText("9");
        boton09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton09MousePressed(evt);
            }
        });

        botonMas.setBackground(new java.awt.Color(153, 153, 153));
        botonMas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        botonMas.setForeground(new java.awt.Color(255, 255, 255));
        botonMas.setText("+");
        botonMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonMasMousePressed(evt);
            }
        });

        boton04.setBackground(new java.awt.Color(153, 153, 153));
        boton04.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton04.setForeground(new java.awt.Color(255, 255, 255));
        boton04.setText("4");
        boton04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton04MousePressed(evt);
            }
        });

        boton05.setBackground(new java.awt.Color(153, 153, 153));
        boton05.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton05.setForeground(new java.awt.Color(255, 255, 255));
        boton05.setText("5");
        boton05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton05MousePressed(evt);
            }
        });

        boton06.setBackground(new java.awt.Color(153, 153, 153));
        boton06.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton06.setForeground(new java.awt.Color(255, 255, 255));
        boton06.setText("6");
        boton06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton06MousePressed(evt);
            }
        });

        botonMenos.setBackground(new java.awt.Color(153, 153, 153));
        botonMenos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        botonMenos.setForeground(new java.awt.Color(255, 255, 255));
        botonMenos.setText("-");
        botonMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonMenosMousePressed(evt);
            }
        });

        boton01.setBackground(new java.awt.Color(153, 153, 153));
        boton01.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton01.setForeground(new java.awt.Color(255, 255, 255));
        boton01.setText("1");
        boton01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton01MousePressed(evt);
            }
        });

        boton02.setBackground(new java.awt.Color(153, 153, 153));
        boton02.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton02.setForeground(new java.awt.Color(255, 255, 255));
        boton02.setText("2");
        boton02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton02MousePressed(evt);
            }
        });

        boton03.setBackground(new java.awt.Color(153, 153, 153));
        boton03.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton03.setForeground(new java.awt.Color(255, 255, 255));
        boton03.setText("3");
        boton03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton03MousePressed(evt);
            }
        });

        botonPor.setBackground(new java.awt.Color(153, 153, 153));
        botonPor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        botonPor.setForeground(new java.awt.Color(255, 255, 255));
        botonPor.setText("*");
        botonPor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonPorMousePressed(evt);
            }
        });

        boton00.setBackground(new java.awt.Color(153, 153, 153));
        boton00.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton00.setForeground(new java.awt.Color(255, 255, 255));
        boton00.setText("0");
        boton00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton00MousePressed(evt);
            }
        });

        botonIgual.setBackground(new java.awt.Color(153, 153, 153));
        botonIgual.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        botonIgual.setForeground(new java.awt.Color(255, 255, 255));
        botonIgual.setText("=");
        botonIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonIgualMousePressed(evt);
            }
        });

        botonDividir.setBackground(new java.awt.Color(153, 153, 153));
        botonDividir.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        botonDividir.setForeground(new java.awt.Color(255, 255, 255));
        botonDividir.setText("/");
        botonDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonDividirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton07, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton08, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton09, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton04, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton05, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton06, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton01, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton02, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton03, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonPor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton07, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton08, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton09, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton04, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton05, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton06, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton01, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton02, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton03, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton00, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton07MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton07MousePressed
        numeroPulsado("7");
    }//GEN-LAST:event_boton07MousePressed

    private void boton08MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton08MousePressed
        numeroPulsado("8");
    }//GEN-LAST:event_boton08MousePressed

    private void boton09MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton09MousePressed
        numeroPulsado("9");
    }//GEN-LAST:event_boton09MousePressed

    private void botonMasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMasMousePressed
        operacionPulsada("+");
    }//GEN-LAST:event_botonMasMousePressed

    private void boton04MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton04MousePressed
        numeroPulsado("4");
    }//GEN-LAST:event_boton04MousePressed

    private void boton05MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton05MousePressed
        numeroPulsado("5");
    }//GEN-LAST:event_boton05MousePressed

    private void boton06MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton06MousePressed
        numeroPulsado("6");
    }//GEN-LAST:event_boton06MousePressed

    private void botonMenosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenosMousePressed
        operacionPulsada("-");
    }//GEN-LAST:event_botonMenosMousePressed

    private void boton01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton01MousePressed
        numeroPulsado("1");
    }//GEN-LAST:event_boton01MousePressed

    private void boton02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton02MousePressed
        numeroPulsado("2");
    }//GEN-LAST:event_boton02MousePressed

    private void boton03MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton03MousePressed
        numeroPulsado("3");
    }//GEN-LAST:event_boton03MousePressed

    private void botonPorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPorMousePressed
        operacionPulsada("*");
    }//GEN-LAST:event_botonPorMousePressed

    private void boton00MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton00MousePressed
        numeroPulsado("0");
    }//GEN-LAST:event_boton00MousePressed

    private void botonIgualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIgualMousePressed
        //leo el segundo operando que está en la pantalla, y lo convierto a double
        double operando2 = Double.valueOf( pantalla.getText()) ;
        
        if (operacion.equals("+")){
            operando1 = operando1 + operando2;
        }
        
        //dibujo en la pantalla el resultado convertido a string
        pantalla.setText(String.valueOf(operando1));
    }//GEN-LAST:event_botonIgualMousePressed

    private void botonDividirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDividirMousePressed
        operacionPulsada("/");
    }//GEN-LAST:event_botonDividirMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton00;
    private javax.swing.JButton boton01;
    private javax.swing.JButton boton02;
    private javax.swing.JButton boton03;
    private javax.swing.JButton boton04;
    private javax.swing.JButton boton05;
    private javax.swing.JButton boton06;
    private javax.swing.JButton boton07;
    private javax.swing.JButton boton08;
    private javax.swing.JButton boton09;
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonMenos;
    private javax.swing.JButton botonPor;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
